# Generated by Django 2.0.6 on 2018-06-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180616_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_thread',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='forum_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Forum_Thread'),
        ),
    ]
